title: "FloatRyde"
description: "Plug-and-play telemetry platform and dynamic vibration analysis for bicycle comfort and setup optimization based on ISO standards."
baseurl: "" # Lascia vuoto se usi dominio custom o username.github.io, oppure metti "/nome-repo"
url: "https://floatryde.it"
permalink: pretty

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag